# Default values for ADMISSION-CONTROLLER.

nameOverride: "" # The name for ADMISSION-CONTROLLER chart<br> (Default: `.Chart.Name`)
controlPlaneLabel: <user input> #K8s control plane label<br> (**REQUIRED**)<br> Example: `node-role.kubernetes.io/master` in case of `kubeadm`/`microk8s.io/cluster` in case of `microk8s`

image:
  svc: 
    registry: <user input> # The image registry where ADMISSION-CONTROLLER image is pushed<br> (**REQUIRED**)
    name: <user input> # The image name with which ADMISSION-CONTROLLER image is pushed to registry<br> (**REQUIRED**)
    pullPolicy: Always  # The pull policy for pulling from container registry for ADMISSION-CONTROLLER<br> (Allowed values: `Always`/`IfNotPresent`)
 
securityContext:
  init: # The fsGroup id for init containers
    fsGroup: 1001 
  iseclController: # The security context for ADMISSION-CONTROLLER Pod
    runAsUser: 1001
    runAsGroup: 1001
    capabilities:
      drop:
        - all
    allowPrivilegeEscalation: false

webhook:
  caBundle: <user input>

service:
  directoryName: admission-controller

storage:
  nfs:
    server: <user input> # The NFS Server IP/Hostname<br> (**REQUIRED**)
    reclaimPolicy: Retain  # The reclaim policy for NFS<br> (Allowed values: `Retain`/)
    accessModes: ReadWriteMany # The access modes for NFS<br> (Allowed values: `ReadWriteMany`)
    path: /mnt/nfs_share # The path for storing persistent data on NFS
    logsSize: 1Gi # The logs size for storing logs for KBS in NFS path
    baseSize: 1Gi # The base volume size (configSize + logSize)
