{{- include "factory.headers" . }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "factory.name" . }}
  namespace: {{ .Release.Namespace }}
data:
  {{- if .Values.global }}
  HVS_URL: {{ .Values.global.hvsUrl }}
  AAS_API_URL: {{ .Values.global.aasUrl }}
  CMS_BASE_URL: {{ .Values.global.cmsUrl }}
  {{- else }}
  HVS_URL: https://{{ .Values.dependentServices.hvs }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.service.hvs.containerPort }}/hvs/v2
  AAS_API_URL: https://{{ .Values.dependentServices.aas }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.service.aas.containerPort }}/aas/v1/
  CMS_BASE_URL: https://{{ .Values.dependentServices.cms }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.service.cms.containerPort }}/cms/v1/
  {{- end}}
  LOG_LEVEL: {{ .Values.config.logLevel }}
  PROVISION_ATTESTATION: "{{ .Values.config.provisionAttestation }}"
  TRUSTAGENT_PORT: "{{ .Values.service.ta.containerPort }}"
  TA_ENABLE_CONSOLE_LOG: "true"
  {{- if .Values.global }}
  {{- if .Values.global.config.nats.enabled }}
  NATS_SERVERS: {{ .Values.global.config.nats.servers }}
  TA_SERVICE_MODE: "{{ .Values.global.config.nats.serviceMode }}"
  {{- end }}
  {{- else if .Values.config.nats.enabled }}
  NATS_SERVERS: {{ .Values.config.nats.servers }}
  TA_SERVICE_MODE: "{{ .Values.config.nats.serviceMode }}"
  {{- end }}
