{{- include "factory.headers" . }}
---
{{- include "factory.serviceCommonSpec" . }}
  {{ if .Values.global.ingress.enable }}
  type: ClusterIP
  ports:
    - port: {{ .Values.service.cms.containerPort }}
      targetPort: {{ .Values.service.cms.containerPort }}
  {{ else }}
  type: NodePort
  ports:
    - port: {{ .Values.service.cms.containerPort }}
      targetPort: {{ .Values.service.cms.containerPort }}
      {{- if .Values.global }}
      nodePort: {{ .Values.global.service.cms }}
      {{- else }}
      nodePort: {{ .Values.service.cms.port }}
      {{- end }}
  {{- end }}