{{- include "factory.headers" . }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "factory.name" . }}-credentials
  namespace: {{ .Release.Namespace }}
stringData:
  SCS_SERVICE_USERNAME: {{ .Values.secret.serviceUsername }}
  SCS_SERVICE_PASSWORD: {{ .Values.secret.servicePassword }}
  {{- if .Values.global }}
  INTEL_PROVISIONING_SERVER_API_KEY: {{ .Values.global.config.intelProvisioningServerApiKey }}
  {{- else }}
  INTEL_PROVISIONING_SERVER_API_KEY: {{ .Values.config.intelProvisioningServerApiKey }}  
  {{- end }}