{{- include "factory.headers" . }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "factory.name" . }}-credentials
  namespace: {{ .Release.Namespace }}
stringData:
  {{- if .Values.global }}
  IHUB_SERVICE_USERNAME: {{ .Values.global.ihub.secret.serviceUsername }}
  IHUB_SERVICE_PASSWORD: {{ .Values.global.ihub.secret.servicePassword }}
  {{- else }}
  IHUB_SERVICE_USERNAME: {{ .Values.secret.serviceUsername }}
  IHUB_SERVICE_PASSWORD: {{ .Values.secret.servicePassword }}
  {{- end}}