{{- include "factory.headers" . }}
---
{{- include "factory.serviceCommonSpec" . }}
  {{ if .Values.global.ingress.enable }}
  type: ClusterIP
  ports:
    - name: {{ .Values.service.natsClient.name }}
      port: {{ .Values.service.natsCluster.containerPort }}
      targetPort: {{ .Values.service.natsCluster.containerPort }}
  {{ else }}
  type: NodePort
  ports:
    - name: {{ .Values.service.natsClient.name }}
      port: {{ .Values.service.natsClient.containerPort }}
    {{- if .Values.global }}
      nodePort: {{ .Values.clientPort }}
    {{- else }}
      nodePort: {{ .Values.service.natsClient.containerPort }}
    {{- end }}
    - name: {{ .Values.service.natsCluster.name }}
      port: {{ .Values.service.natsCluster.containerPort }}
  {{ end }}