# Default values for shvs

nameOverride: "" # The name for SHVS chart<br> (Default: `.Chart.Name`)
controlPlaneHostname: <user input> # K8s control plane IP/Hostname<br> (**REQUIRED**)

# Warning: Ensure that the naming is applied consistently for all dependent services when modifying nameOverride
# TODO: Services should be be able to be deployed in different namespaces
dependentServices: # The dependent Service Name for deploying  SHVS chart, default is the chart name and override is from nameOverride value.
  cms: cms
  aas: aas
  scs: scs

config:
  envVarPrefix: SHVS
  dbPort: 5432 # PostgreSQL DB port
  dbSSL: on # PostgreSQL DB SSL<br> (Allowed Values: `on`/`off`)
  dbSSLCert: /etc/postgresql/secrets/server.crt # PostgreSQL DB SSL Cert
  dbSSLKey: /etc/postgresql/secrets/server.key  # PostgreSQL DB SSL Key
  dbSSLCiphers: ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256 # PostgreSQL DB SSL Ciphers
  dbListenAddresses: "*" # PostgreSQL DB Listen Address
  dbName: shvsdb # SHVS DB Name
  dbMaxConnections: 200 # Determines the maximum number of concurrent connections to the database server. Default is 200
  dbSharedBuffers: 2GB # Determines how much memory is dedicated to PostgreSQL to use for caching data. Default is 2GB
  dbSSLMode: verify-full # PostgreSQL DB SSL Mode
  dbhostSSLPodRange: 10.1.0.0/8 # PostgreSQL DB Host Address(IP address/subnet-mask). IP range varies for different k8s network plugins(Ex: Flannel - 10.1.0.0/8 (default), Calico - 192.168.0.0/16).

# The values provided for serviceUsername and servicePassword here should be same as that of provided for aas.shvs.secret.serviceUsername and aas.shvs.secret.servicePassword in values.yaml file for aas-manager chart
secret:
  adminUsername: # Install Admin Username for SHVS
  adminPassword: # Install Admin Password for SHVS
  dbUsername: # DB Username for SHVS DB
  dbPassword: # DB Password for SHVS DB 
  serviceUsername: # Service Username for SHVS
  servicePassword: # Service Username for SHVS

aas:
  url: <user input> # Please update the url section if shvs is exposed via ingress
  secret:
    adminUsername: # Admin Username for AAS
    adminPassword: # Admin Password for AAS

image:
  db:
    registry: dockerhub.io # The image registry where PostgreSQL image is pulled from
    name: postgres:14.2 # The image name of PostgreSQL
    pullPolicy: Always # The pull policy for pulling from container registry for PostgreSQL image
  svc:
    name: <user input> # The image name with which SHVS image is pushed to registry<br> (**REQUIRED**)
    pullPolicy: Always # The pull policy for pulling from container registry for SHVS<br> (Allowed values: `Always`/`IfNotPresent`)
    imagePullSecret: <user input> # The image pull secret for authenticating with image registry, can be left empty if image registry does not require authentication
    initName: <user input> # The image name of init container
  aasManager:
    name: <user input> # The image name with which AAS-Manager image is pushed to registry<br> (**REQUIRED**)
    pullPolicy: Always # The pull policy for pulling from container registry for AAS-Manager<br> (Allowed values: `Always`/`IfNotPresent`)
    imagePullSecret: <user input> # The image pull secret for authenticating with image registry, can be left empty if image registry does not require authentication

storage:
  nfs:
    server: <user input> # The NFS Server IP/Hostname<br> (**REQUIRED**)
    reclaimPolicy: Retain # The reclaim policy for NFS<br> (Allowed values: `Retain`/)
    accessModes: ReadWriteMany # The access modes for NFS<br> (Allowed values: `ReadWriteMany`)
    path: /mnt/nfs_share # The path for storing persistent data on NFS
    dbSize: 5Gi # The DB size for storing DB data for SHVS in NFS path
    configSize: 10Mi # The configuration size for storing config for SHVS in NFS path
    logsSize: 1Gi # The logs size for storing logs for SHVS in NFS path
    baseSize: 6.1Gi # The base volume size (configSize + logSize + dbSize)

securityContext:
  shvsdbInit: # The fsGroup id for init containers for SHVS DB
    fsGroup: 2000
  shvsdb: # The security content for SHVS DB Service Pod
    runAsUser: 1001
    runAsGroup: 1001
  shvsInit: # The fsGroup id for init containers for SHVS
    fsGroup: 1001
  shvs: # The security content for SHVS Pod
    runAsUser: 1001
    runAsGroup: 1001
    capabilities:
      drop:
        - all
    allowPrivilegeEscalation: false

service:
  directoryName: shvs
  cms:
    containerPort: 8445 # The containerPort on which CMS can listen
  aas: 
    containerPort: 8444 # The containerPort on which AAS can listen
    port: 30444 # The externally exposed NodePort on which AAS can listen to external traffic
  scs:
    containerPort: 9000 # The containerPort on which SCS can listen 
    port: 30502 # The externally exposed NodePort on which SCS can listen to external traffic    
  shvsdb:
    containerPort: 5432 # The containerPort on which SHVS DB can listen 
  shvs:
    containerPort: 13000 # The containerPort on which SHVS can listen 
    port: 30500 # The externally exposed NodePort on which SHVS can listen to external traffic
  ingress:
    enable: false # Accept true or false to notify ingress rules are enable or disabled

log:
  loglevel: info