{{- include "factory.headers" . }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: cms-tls-cert-sha384
  namespace: {{ .Release.Namespace }}
stringData:
  {{- if .Values.global }}
  CMS_TLS_CERT_SHA384: {{ .Values.global.cmsTlsSha384 }}
  {{- else }}
  CMS_TLS_CERT_SHA384: {{ .Values.cmsTlsSha384 }}
  {{- end }}