---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "factory.name" .}}-credentials
  namespace: {{ .Release.Namespace }}
stringData:
  CCC_ADMIN_USERNAME: {{ .Values.secret.cccAdminUsername }}
  CCC_ADMIN_PASSWORD: {{ .Values.secret.cccAdminPassword }}