{{- if contains "Trusted-Workload-Placement-Cloud-Service-Provider" .Template.BasePath }}
{{- include "factory.headers" . }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: cms-tls-cert-sha384
  namespace: {{ .Release.Namespace }}
stringData:
  CMS_TLS_CERT_SHA384: {{ .Values.global.cmsTlsSha384 }}
{{- end }}