{{- include "factory.headers" . }}
---
{{- include "factory.deploymentCommonSpec" . }}
    spec:
      {{- if .Values.global }}
      {{- if .Values.global.image.imagePullSecret }}
      imagePullSecrets:
      - name: {{ .Values.global.image.imagePullSecret }}
      {{- end }}
      {{- else }}
      {{- if .Values.image.svc.imagePullSecret }}
      imagePullSecrets:
      - name: {{ .Values.image.svc.imagePullSecret }}
      {{- end }}
      {{- end }}
      initContainers:
        {{- include "factory.initWaitForCmsSha384BearerToken" . | nindent 8 }}
        {{- include "factory.initCommonSpecLinkServiceVolumes" . | nindent 8 }}
          securityContext:
            {{- toYaml .Values.securityContext.qvs | nindent 12 }}
          volumeMounts:
            {{- include "factory.volumeMountsBasePv" . | nindent 12 }}
      containers:
        - name: {{ include "factory.name" . }}
          {{- include "factory.imageContainer" . | indent 10 }}
          securityContext:
            {{- toYaml .Values.securityContext.qvs | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "factory.name" . }}
          env:
            {{- include "factory.envCmsSha384" . | nindent 12 }}
          ports:
            - containerPort: {{ .Values.service.qvs.containerPort }}
          readinessProbe:
            httpGet:
              path: /qvs/v1/version
              port: {{ .Values.service.qvs.containerPort }}
              scheme: HTTPS            
            initialDelaySeconds: 1
            failureThreshold: 30
            periodSeconds: 5
          envFrom:
            - configMapRef:
                name: {{ include "factory.name" . }} 
          volumeMounts:
            {{- include "factory.volumeMountSvcConfig" . | nindent 12 }}
            {{- include "factory.volumeMountSvcLogs" . | nindent 12 }}
            {{- include "factory.volumeMountSecrets" . | nindent 12 }}
            - name: {{ include "factory.name" . }}-sgx-qcnl
              mountPath: /etc/sgx_default_qcnl.conf
              subPath: sgx_default_qcnl.conf 
      volumes:
        {{- include "factory.volumeSvcConfig" . | nindent 8 }}
        {{- include "factory.volumeSvcLogs" . | nindent 8 }}
        {{- include "factory.volumesBasePV" . | nindent 8 }}
        {{- include "factory.volumeProjectedSecrets" . | nindent 8 }}
        {{- include "factory.volumeAasBearerToken" . | nindent 12 }}
        - name: {{ include "factory.name" . }}-sgx-qcnl
          configMap:
            name: {{ include "factory.name" . }}
