# Default values for WLA.

nameOverride: "" # The name for WLA chart<br> (Default: `.Chart.Name`)
controlPlaneHostname: <user input> # K8s control plane IP/Hostname<br> (**REQUIRED**)
#hardwareFeature: <user input> # The enabled hardware feature on the host<br> (**REQUIRED**)<br> (Allowed Values: `TXT`/`SUEFI`)

# Warning: Ensure that the naming is applied consistently for all dependent services when modifying nameOverride
# TODO: Services should be be able to be deployed in different namespaces
dependentServices: # The dependent Service Name for deploying  WLA chart, default is the chart name and override is from nameOverride value.
  cms: cms
  aas: aas
  hvs: hvs
  wls: wls
  ta: ta

nodeLabel:
  txt: "" # The node label for TXT-ENABLED hosts<br> (**REQUIRED IF NODE IS TXT ENABLED**)
  suefi: "" # The node label for SUEFI-ENABLED hosts (**REQUIRED IF NODE IS SUEFI ENABLED**)

image:
  svc:
    name: <user input> # The image name with which WLA image is pushed to registry<br> (**REQUIRED**)
    pullPolicy: Always # The pull policy for pulling from container registry for WLA <br> (Allowed values: `Always`/`IfNotPresent`)
    imagePullSecret:  # The image pull secret for authenticating with image registry, can be left empty if image registry does not require authentication
    initName: <user input> 
  aasManager:
    name: <user input> # The image registry where AAS Manager image is pushed<br> (**REQUIRED**)
    pullPolicy: Always # The pull policy for pulling from container registry for AAS Manager <br> (Allowed values: `Always`/`IfNotPresent`)
    imagePullSecret:  # The image pull secret for authenticating with image registry, can be left empty if image registry does not require authentication

config:
  logLevel: info  # Log Level for Trust agent<br> (Allowed values: `info`/`warn`/`debug`/`trace`)
  #nodeLabel: <user input> # The node label based on hardware-feature enabled<br> (**REQUIRED**)

aas:
# Please update the url section if aas is exposed via ingress
  url:
  secret: 
    adminUsername: # Admin Username for AAS
    adminPassword: # Admin Password for AAS

    # The values provided for adminUsername and adminPassword here should be same as that of provided for aas.secret.adminUsername and aas.secret.adminPassword in values.yaml file for ihub chart
    #


secret:
  installAdminUsername: # Admin Username for WLS
  installAdminPassword: # Admin Password for WLS
  serviceUsername:  # Service Username for workload-agent
  servicePassword:  # Service Password for workload-agent

securityContext:
  aasManager: # The security content for AAS-MANAGER Pod
    runAsUser: 1001
    runAsGroup: 1001
    capabilities:
      drop:
        - all
    allowPrivilegeEscalation: false
  aasManagerInit: # The fsGroup id for init containers for AAS DB
    fsGroup: 1001

service:
  directoryName: workload-agent
  cms:
    containerPort: 8445 # The containerPort on which CMS can listen
  aas: 
    containerPort: 8444 # The containerPort on which AAS can listen
  hvs:
    containerPort: 8443 # The containerPort on which HVS can listen 
  wls:
    containerPort: 5000 # The containerPort on which WLS can listen 
