{{- include "factory.headers" . }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "factory.name" . }}
  namespace: {{ .Release.Namespace }}
data:
   AAS_BASE_URL: https://{{ .Values.dependentServices.aas }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.service.aas.containerPort }}/aas/v1
   CMS_BASE_URL: https://{{ .Values.dependentServices.cms }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.service.cms.containerPort }}/cms/v1
   INTEL_PCS_SGX_URL: {{ .Values.config.intelPcsUrl }}
   DB_HOST: {{ include "factory.name" . }}db.{{ .Release.Namespace }}.svc.cluster.local
   DB_PORT: {{ .Values.config.dbPort | quote }}
   DB_NAME: {{ .Values.config.dbName }}
   DB_SSL_MODE: {{ .Values.config.dbSSLMode }}
   DB_SSL_CERT_SOURCE: {{ .Values.config.dbSSLCert }}
   RETRY_COUNT: {{ .Values.config.retryCount | quote }}
   WAIT_TIME: {{ .Values.config.waitTime | quote }}
   REFRESH_INTERVAL: {{ .Values.config.refreshInterval | quote }}
   {{- if .Values.global }}
   TLS_SAN_LIST: {{ .Values.global.controlPlaneHostname }},{{ include "factory.name" . }}.{{ .Release.Namespace }}.svc.cluster.local
   {{- else }}
   TLS_SAN_LIST: {{ .Values.controlPlaneHostname }},{{ include "factory.name" . }}.{{ .Release.Namespace }}.svc.cluster.local
   {{- end }}