# Default values for QVS.

nameOverride: "" # The name for QVS chart<br> (Default: `.Chart.Name`)
controlPlaneHostname: # K8s control plane IP/Hostname<br> (**REQUIRED**)

# Warning: Ensure that the naming is applied consistently for all dependent services when modifying nameOverride
# TODO: Services should be be able to be deployed in different namespaces
dependentServices: # The dependent Service Name for deploying  Quote Verification Service chart, default is the chart name and override is from nameOverride value.
  cms: cms
  aas: aas
  tcs: tcs

image:
  svc:
    name: <user input> # The image registry where QVS image is pushed<br> (**REQUIRED**)
    pullPolicy: Always # The pull policy for pulling from container registry for QVS <br> (Allowed values: `Always`/`IfNotPresent`)
    imagePullSecret:  # The image pull secret for authenticating with image registry, can be left empty if image registry does not require authentication
    initName:
  aasManager:
    name: <user input> # The image registry where AAS Manager image is pushed<br> (**REQUIRED**)
    pullPolicy: Always # The pull policy for pulling from container registry for AAS Manager <br> (Allowed values: `Always`/`IfNotPresent`)
    imagePullSecret:  # The image pull secret for authenticating with image registry, can be left empty if image registry does not require authentication

storage:
  nfs:
    server: <user input> # The NFS Server IP/Hostname<br> (**REQUIRED**)
    reclaimPolicy: Retain  # The reclaim policy for NFS<br> (Allowed values: `Retain`/)
    accessModes: ReadWriteMany # The access modes for NFS<br> (Allowed values: `ReadWriteMany`)
    path: /mnt/nfs_share # The path for storing persistent data on NFS
    configSize: 10Mi # The configuration size for storing config for QVS in NFS path
    logsSize: 1Gi # The logs size for storing logs for QVS in NFS path
    baseSize: 1.1Gi # The base volume size (configSize + logSize)

aas:
# Please update the url section if aas is exposed via ingress
  url:
  secret: 
    adminUsername:  # Admin Username for AAS
    adminPassword:  # Admin Password for AAS

    # The values provided for adminUsername and adminPassword here should be same as that of provided for aas.secret.adminUsername and aas.secret.adminPassword in values.yaml file for ihub chart
    #
secret:
  installAdminUsername: # Super Admin Username for QVS
  installAdminPassword: # Super Admin Password for QVS

securityContext:
  init: # The fsGroup id for init containers
    fsGroup: 1001 
  qvs: # The security content for QVS Pod
    runAsUser: 1001
    runAsGroup: 1001
    capabilities:
      drop:
        - all
    allowPrivilegeEscalation: false
  aasManager: # The security content for AAS-MANAGER Pod
    runAsUser: 1001
    runAsGroup: 1001
    capabilities:
      drop:
        - all
    allowPrivilegeEscalation: false
  aasManagerInit: # The fsGroup id for init containers for AAS DB
    fsGroup: 1001

config:
  qplHttps: false #variable to use update USE_SECURE variable in sgx_default_qcnl.conf to enable https by default it is false
      
service:
  directoryName: qvs
  cms:
    containerPort: 8445 # The containerPort on which CMS can listen to traffic
  aas:
    containerPort: 8444 # The containerPort on which AAS can listen to traffic
  tcs:
    containerPort: 9000 # The containerPort on which TCS can listen to traffic
  qvs: 
    isSandBoxEnv: "no" # If SGX node which runs client (SKC client/ SGX Agent) is production grade then mark it "no", else mark it "yes".
    containerPort: 12000 # The containerPort on which QVS can listen to traffic
    port: 30501 # The externally exposed NodePort on which QVS can listen to external traffic
  ingress:
    enable: false
