# Default values for FDS.

nameOverride: "" # The name for FDS chart<br> (Default: `.Chart.Name`)
controlPlaneHostname: <user input> # K8s control plane IP/Hostname<br> (**REQUIRED**)

# Warning: Ensure that the naming is applied consistently for all dependent services when modifying nameOverride
# TODO: Services should be able to be deployed in different namespaces
dependentServices: # The dependent Service Name for deploying FDS chart, default is the chart name and override is from nameOverride value.
  cms: cms
  aas: aas

config:
  dbPort: 5432 # PostgreSQL DB port
  dbSSL: on # PostgreSQL DB SSL<br> (Allowed Values: `on`/`off`)
  dbSSLCert: /etc/postgresql/secrets/server.crt # PostgreSQL DB SSL Cert
  dbSSLKey: /etc/postgresql/secrets/server.key  # PostgreSQL DB SSL Key
  dbSSLCiphers: ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256 # PostgreSQL DB SSL Ciphers
  dbListenAddresses: "*" # PostgreSQL DB Listen Address
  dbName: fdsdb # FDS DB Name
  dbhostSSLPodRange: 10.1.0.0/8 # PostgreSQL DB Host Address(IP address/subnet-mask). IP range varies for different k8s network plugins(Ex: Flannel - 10.1.0.0/8 (default), Calico - 192.168.0.0/16).
  dbSSLMode: verify-full # PostgreSQL DB SSL Mode

aas:
# Please update the url section if aas is exposed via ingress
  url:
  secret: 
    adminUsername: # Admin Username for AAS
    adminPassword: # Admin Password for AAS

    # The values provided for adminUsername and adminPassword here should be same as that of provided for aas.secret.adminUsername and aas.secret.adminPassword in values.yaml file for ihub chart
    #

secret:
  dbUsername: # DB Username for FDS DB
  dbPassword: # DB Password for FDS DB
  installAdminUsername:  # Admin Username for HVS
  installAdminPassword:  # Admin Password for HVS

image:
  db:
    registry: dockerhub.io # The image registry where PostgreSQL image is pulled from
    name: postgres:11.7 # The image name of PostgreSQL
    pullPolicy: Always # The pull policy for pulling from container registry for PostgreSQL image
  svc:
    name: <user input> # The image registry where FDS image is pushed<br> (**REQUIRED**)
    pullPolicy: Always # The pull policy for pulling from container registry for FDS <br> (Allowed values: `Always`/`IfNotPresent`)
    imagePullSecret:  # The image pull secret for authenticating with image registry, can be left empty if image registry does not require authentication
    initName: <user input> 
  aasManager:
    name: <user input> # The image registry where AAS Manager image is pushed<br> (**REQUIRED**)
    pullPolicy: Always # The pull policy for pulling from container registry for AAS manager <br> (Allowed values: `Always`/`IfNotPresent`)
    imagePullSecret:  # The image pull secret for authenticating with image registry, can be left empty if image registry does not require authentication

storage:
  nfs:
    server: <user input> # The NFS Server IP/Hostname<br> (**REQUIRED**)
    reclaimPolicy: Retain  # The reclaim policy for NFS<br> (Allowed values: `Retain`/)
    accessModes: ReadWriteMany # The access modes for NFS<br> (Allowed values: ReadWriteMany)
    path: /mnt/nfs_share # The path for storing persistent data on NFS
    dbSize: 5Gi # The DB size for storing DB data for FDS in NFS path
    configSize: 10Mi # The configuration size for storing config for FDS in NFS path
    logsSize: 1Gi # The logs size for storing logs for FDS in NFS path
    baseSize: 1.1Gi # The base volume size (configSize + logSize)
 
securityContext:
  fdsdbInit: # The fsGroup id for init containers for FDS DB
    fsGroup: 2000
  fdsdb: # The security content for FDS DB Service Pod
    runAsUser: 1001
    runAsGroup: 1001
  fdsInit: # The fsGroup id for init containers for FDS
    fsGroup: 1001 
  fds: # The security content for FDS Pod
    runAsUser: 1001
    runAsGroup: 1001
    capabilities:
      drop:
        - all
    allowPrivilegeEscalation: false
  aasManager: # The security content for AAS-MANAGER Pod
    runAsUser: 1001
    runAsGroup: 1001
    capabilities:
      drop:
        - all
    allowPrivilegeEscalation: false
  aasManagerInit: # The fsGroup id for init containers for AAS DB
    fsGroup: 1001
service:
  directoryName: fds # The path name to be appended to all mount paths of the service
  cms:
    containerPort: 8445 # The containerPort on which CMS can listen
  aas: 
    containerPort: 8444 # The containerPort on which AAS can listen
    port: 30444 # The externally exposed NodePort on which AAS can listen to external traffic
  fdsdb:
      containerPort: 5432 # The containerPort on which FDS DB can listen
  fds:
    containerPort: 13000 # The containerPort on which FDS can listen
    port: 30500 # The externally exposed NodePort on which FDS can listen to external traffic
  ingress:
    enable: false # Accept true or false to notify ingress rules are enable or disabled
