{{- include "factory.headers" . }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "factory.name" . }}-opt
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: nfs
  accessModes:
    - {{ .Values.storage.nfs.accessModes }}
  resources:
    requests:
      storage: {{ .Values.storage.nfs.homeDirSize }}