{{- include "factory.headers" . }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "factory.name" . }}-credentials
  namespace: {{ .Release.Namespace }}
stringData:
  KBS_SERVICE_USERNAME: {{ .Values.secret.serviceUsername }}
  KBS_SERVICE_PASSWORD: {{ .Values.secret.servicePassword }}