{{- include "factory.headers" . }}
---
{{- include "factory.deploymentCommonSpec" . }}
    spec:
      securityContext:
        fsGroup: 1001
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: {{ include "factory.name" . }}
      containers:
        - name: server
          {{- include "factory.imageContainer" . | indent 10 }}
          securityContext:
            {{- toYaml .Values.securityContext.admissionController | nindent 12 }}
          ports:
            - containerPort: 8889
              name: tls
            - containerPort: 80
              name: metrics
          env:
            - name: PORT
              value: "8889"
            - name: LOG_LEVEL
              value: "INFO"
            - name: LOG_MAX_LENGTH
              value: "1500"
          volumeMounts:
            - name: {{ include "factory.name" . }}-certs
              mountPath: /etc/webhook/certs/
              readOnly: true
            {{- include "factory.volumeMountSvcLogs" . | nindent 12 }}
      volumes:
        - name: {{ include "factory.name" . }}-certs
          secret:
            secretName: {{ include "factory.name" . }}-certs
        {{- include "factory.volumeSvcLogs" . | nindent 8 }}
        {{- include "factory.volumesBasePV" . | nindent 8 }}
