{{- include "factory.headers" . }}
---
{{- include "factory.deploymentCommonSpec" . }}
    spec:
      {{- if .Values.global }}
      {{- if .Values.global.image.imagePullSecret }}
      imagePullSecrets:
      - name: {{ .Values.global.image.imagePullSecret }}
      {{- end }}
      {{- else }}
      {{- if .Values.image.svc.imagePullSecret }}
      imagePullSecrets:
      - name: {{ .Values.image.svc.imagePullSecret }}
      {{- end }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.securityContext.init | nindent 8 }}
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: {{ include "factory.name" . }}
      containers:
        - name: server
          {{- include "factory.imageContainer" . | indent 10 }}
          securityContext:
            {{- toYaml .Values.securityContext.admissionController | nindent 12 }}
          ports:
            - containerPort: {{ .Values.service.admissionController.containerPort }}
              name: tls
            - containerPort: {{ .Values.service.admissionController.httpPort }}
              name: metrics
          env:
            - name: PORT
              value: "{{ .Values.service.admissionController.containerPort }}"
            - name: LOG_LEVEL
              value: "INFO"
            - name: LOG_MAX_LENGTH
              value: "1500"
          volumeMounts:
            - name: {{ include "factory.name" . }}-certs
              mountPath: /etc/webhook/certs/
              readOnly: true
            {{- include "factory.volumeMountSvcLogs" . | nindent 12 }}
      volumes:
        - name: {{ include "factory.name" . }}-certs
          secret:
            secretName: {{ include "factory.name" . }}-certs
        {{- include "factory.volumeSvcLogs" . | nindent 8 }}
        {{- include "factory.volumesBasePV" . | nindent 8 }}
