apiVersion: v1
kind: ServiceAccount
metadata:
  name: admission-controller
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "factory.name" . }}
rules:
  - apiGroups: [""]
    resources: ["nodes","nodes/status","nodes/metrics"]
    verbs: ["post","get", "list", "watch", "update", "patch", "delete"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "factory.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "factory.name" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: admission-controller
  apiGroup: rbac.authorization.k8s.io
