{{- include "factory.headers" . }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "factory.name" . }}
  namespace: {{ .Release.Namespace }}
data:
  AAS_API_URL: https://{{ .Values.dependentServices.aas }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.service.aas.containerPort }}/aas/v1
  CMS_BASE_URL: https://{{ .Values.dependentServices.cms }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.service.cms.containerPort }}/cms/v1
  SCS_BASE_URL: https://{{ .Values.dependentServices.scs }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.service.scs.containerPort }}/scs/sgx/
  {{- if .Values.global }}
  SAN_LIST: {{ .Values.global.controlPlaneHostname }},{{ include "factory.name" . }}.{{ .Release.Namespace }}.svc.cluster.local
  {{- else }}
  SAN_LIST: {{ .Values.controlPlaneHostname }},{{ include "factory.name" . }}.{{ .Release.Namespace }}.svc.cluster.local
  {{- end }}
  SHVS_DB_HOSTNAME: {{ include "factory.name" . }}db.{{ .Release.Namespace }}.svc.cluster.local
  SHVS_DB_NAME: {{ .Values.config.dbName }}
  SHVS_DB_SSLCERTSRC: {{ .Values.config.dbSSLCert }}
  SHVS_DB_PORT: {{ .Values.config.dbPort | quote }}
