# Default values for APS.

nameOverride: "" # The name for APS chart<br> (Default: `.Chart.Name`)


# Warning: Ensure that the naming is applied consistently for all dependent services when modifying nameOverride
# TODO: Services should be be able to be deployed in different namespaces
dependentServices: # The dependent Service Name for deploying Attestation Policy Service chart, default is the chart name and override is from nameOverride value.
  cms: cms
  aas: aas
  qvs: qvs

controlPlaneHostname: <user input> # K8s control plane IP/Hostname<br> (**REQUIRED**)

#APS db settings
config:
  envVarPrefix: APS
  dbPort: 5432 # PostgreSQL DB port
  dbSSL: on # PostgreSQL DB SSL<br> (Allowed: `on`/`off`)
  #TODO: to remove the below values if hardcoding the path
  dbSSLCert: /etc/postgresql/secrets/server.crt # PostgreSQL DB SSL Cert
  dbSSLKey: /etc/postgresql/secrets/server.key # PostgreSQL DB SSL Key
  dbSSLCiphers: ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256 # PostgreSQL DB SSL Ciphers
  dbListenAddresses: "*" # PostgreSQL DB Listen Address
  dbName: aps_db # APS DB Name
  dbSSLMode: verify-full # PostgreSQL DB SSL Mode
  vender: postgres
  dbhostSSLPodRange: 10.1.0.0/8 # PostgreSQL DB Host Address(IP address/subnet-mask). IP range varies for different k8s network plugins(Ex: Flannel - 10.1.0.0/8 (default), Calico - 192.168.0.0/16).
  dbSSLCertSource: /etc/postgresql/secrets/server.crt

aas:
# Please update the url section if aas is exposed via ingress
  url:
  secret: 
    adminUsername:  # Admin Username for AAS
    adminPassword:  # Admin Password for AAS

    # The values provided for adminUsername and adminPassword here should be same as that of provided for aas.secret.adminUsername and aas.secret.adminPassword in values.yaml file for ihub chart
    #

secret:
  dbUsername: # DB Username for APS DB
  dbPassword: # DB Password for APS DB
  installAdminUsername: # Admin Username for APS
  installAdminPassword: # Admin Password for APS
  serviceUsername: 
  servicePassword: 

image:
  
  db:
    registry: dockerhub.io # The image registry where PostgreSQL image is pulled from
    name: postgres:14.2 # The image name of PostgreSQL
    pullPolicy: Always # The pull policy for pulling from container registry for PostgreSQL image<br> (Allowed values: `Always`/`IfNotPresent`)
  svc:
    name: <user input> # The image registry where APS image is pushed<br> (**REQUIRED**)
    pullPolicy: Always # The pull policy for pulling from container registry for APS <br> (Allowed values: `Always`/`IfNotPresent`)
    imagePullSecret:  # The image pull secret for authenticating with image registry, can be left empty if image registry does not require authentication
    initName: <user input> 
  aasManager:
    name: <user input> # The image registry where AAS Manager image is pushed<br> (**REQUIRED**)
    pullPolicy: Always # The pull policy for pulling from container registry for AAS Manager<br> (Allowed values: `Always`/`IfNotPresent`)
    imagePullSecret:  # The image pull secret for authenticating with image registry, can be left empty if image registry does not require authentication

storage:
  nfs:
    server: <user input> # The NFS Server IP/Hostname<br> (**REQUIRED**)
    reclaimPolicy: Retain # The reclaim policy for NFS<br> (Allowed values: `Retain`/)
    accessModes: ReadWriteMany # The access modes for NFS<br> (Allowed values: `ReadWriteMany`)
    path: /mnt/nfs_share # The path for storing persistent data on NFS
    dbSize: 5Gi # The DB size for storing DB data for HVS in NFS path
    configSize: 10Mi # The configuration size for storing config for HVS in NFS path
    logsSize: 1Gi # The logs size for storing logs for HVS in NFS path
    baseSize: 6.1Gi # The base volume size (configSize + logSize + dbSize)

securityContext:
  apsdbInit: # The fsGroup id for init containers for FDS DB
    fsGroup: 2000
  apsdb: # The security content for FDS DB Service Pod
    runAsUser: 1001
    runAsGroup: 1001
  apsInit: # The fsGroup id for init containers for FDS
    fsGroup: 1001 
  aps: # The security content for FDS Pod
    runAsUser: 1001
    runAsGroup: 1001
    capabilities:
      drop:
        - all
    allowPrivilegeEscalation: false
      
service:
  directoryName: aps
  cms:
    containerPort: 8445 # The containerPort on which CMS can listen
    port: 30445 # The externally exposed NodePort on which CMS can listen to external traffic

  aas:
    containerPort: 8444 # The containerPort on which AAS can listen
    port: 30444 # The externally exposed NodePort on which AAS can listen to external traffic

  qvs: 
    containerPort: 12000 # The containerPort on which QVS can listen to traffic
    port: 30501 # The externally exposed NodePort on which QVS can listen to external traffic

  aps: 
    containerPort: 5443 # The containerPort on which APS can listen to traffic
    port: 30503 # The externally exposed NodePort on which APS can listen to external traffic
  
  apsdb:
    containerPort: 5432 # The containerPort on which apsdb can listen to traffic
  
  ingress:
    enable: false # Accept true or false to notify ingress rules are enable or disabled
