{{- include "factory.headers" . }}
---
{{- include "factory.deploymentCommonSpec" . }}
    spec:
      {{- if .Values.global }}
      {{- if .Values.global.image.imagePullSecret }}
      imagePullSecrets:
      - name: {{ .Values.global.image.imagePullSecret }}
      {{- end }}
      {{- else }}
      {{- if .Values.image.svc.imagePullSecret }}
      imagePullSecrets:
      - name: {{ .Values.image.svc.imagePullSecret }}
      {{- end }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.securityContext.sqvsInit | nindent 8 }}
      serviceAccountName: {{ include "factory.name" . }}
      initContainers:
        {{- include "factory.initWaitForCmsSha384BearerToken" . | nindent 8 }}
        {{- include "factory.initCommonSpecLinkServiceVolumes" . | nindent 8 }}
          securityContext:
            {{- toYaml .Values.securityContext.sqvs | nindent 12 }}
          volumeMounts:
            {{- include "factory.volumeMountsBasePv" . | nindent 12 }}
      containers:
        - name: {{ include "factory.name" . }}
          {{- include "factory.imageContainer" . | indent 10 }}
          securityContext:
            {{- toYaml .Values.securityContext.sqvs | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "factory.name" . }}
          env:
            {{- include "factory.envCmsSha384" . | nindent 12 }}
          ports:
            - containerPort: {{ .Values.service.sqvs.containerPort }}
          readinessProbe:
            httpGet:
              path: /svs/v1/version
              port: {{ .Values.service.sqvs.containerPort }}
              scheme: HTTPS
            initialDelaySeconds: 5
            failureThreshold: 60
            periodSeconds: 15
          volumeMounts:
          {{- include "factory.volumeMountSvcConfig" . | nindent 12 }}
          {{- include "factory.volumeMountSvcLogs" . | nindent 12 }}
          {{- include "factory.volumeMountSecrets" . | nindent 12 }}
            - name: trusted-rootca-file
              mountPath: /tmp/
      volumes:
        {{- include "factory.volumeSvcConfig" . | nindent 8 }}
        {{- include "factory.volumeSvcLogs" . | nindent 8 }}
        {{- include "factory.volumesBasePV" . | nindent 8 }}
        {{- include "factory.volumeProjectedSecrets" . | nindent 8 }}
        {{- include "factory.volumeCredentials" . | nindent 12 }}
        {{- include "factory.volumeAasBearerToken" . | nindent 12 }}
        - name: trusted-rootca-file        
          secret:
            secretName: {{ include "factory.name" . }}-trusted-rootca