{{- include "factory.headers" . }}
---
{{- include "factory.serviceCommonSpec" . }}
  {{ if .Values.global.ingress.enable }}
  type: ClusterIP
  ports:
    - port: {{ .Values.service.hvs.containerPort }}
      targetPort: {{ .Values.service.hvs.containerPort }}
  {{ else }}
  type: NodePort
  ports:
    - port: {{ .Values.service.hvs.containerPort }}
      targetPort: {{ .Values.service.hvs.containerPort }}
      {{- if .Values.global }}
      nodePort: {{ .Values.global.service.hvs }}
      {{- else }}
      nodePort: {{ .Values.service.hvs.port }}
      {{- end }}
  {{ end }}