# Default values for cleanup-secrets.

nameOverride: "" # The name for CLEANUP-JOBS chart (Default: .Chart.Name)

securityContext:
  cleanupJobsInit: # The fsGroup id for init containers for cleanup jobs
    fsGroup: 1001
  cleanupJobs: # The security content for Cleanup jobs job
    runAsUser: 1001
    runAsGroup: 1001
    capabilities:
      drop:
        - all
    allowPrivilegeEscalation: false