name: OnPullRequest

on:
  pull_request:

jobs:
  lint:
    runs-on: [ self-hosted ]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Lint Helm Charts
      run: make lint
